

关于:
用力:
分支: [ “主”, “主人” ]
workflow_dispatch:

工作:
建造:
继续: Windows-最新
    
步骤:
    - 名称: 结出仓库
用途: 动作/checkout@v4
    

用途: 作/设置python@v5
其中:

    
    - 名称: 安装依赖
跑: |
Python -m pip install --upgrade pip
pip install pyinstaller PyQt5 pygame mutagen opencv-python numpy
    

跑: |

    


其中:

